name: commitlint_lint
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  commitlint_types:
  conventional_commit: ^0.5.0+1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
