name: commitlint_load
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
