name: commitlint_ensure
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 change_case: ^1.0.0+3
 commitlint_types:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
